version: '3'

services:

  postgres:
    image: postgres:13
    container_name: postgres13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=**postgres@odoo**
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db

volumes:
  postgres-data:

networks:
  db:
    external:
      name: db
